---
title: "MATH167R: Statistical Programming with R"
tbl-colwidths: [5,10,20,10,10,10]
---

::: column-screen-inset-right
|          Week           | Date    | Topic                                 |                                   Slides                                    |                              Check-in                               |                                                               Lab                                                               |
|:-----------------------:|---------|---------------------------------------|:---------------------------------------------------------------------------:|:-------------------------------------------------------------------:|:-------------------------------------------------------------------------------------------------------------------------------:|
| [1](/weeks/week-1.html) | M 8/21  | Course Overview and Introduction to R |          [Slides 01](slides/01_overview.html){.label .label-green}          | [Check-in 01](checkins/01_first-checkin.html){.label .label-purple} |                                                                                                                                 |
|                         | W 8/23  | R fundamentals                        |      [Slides 02](slides/02_objects-classes.html){.label .label-green}       |                                                                     | [Lab 01](https://raw.githubusercontent.com/math167R-f23/math167R-f23.github.io/main/labs/01_first-R-lab.Rmd){.label .label-red} |
|            2            | M 8/28  | R fundamentals                        | [Slides 03](slides/03_functions-vectors-matrices.html){.label .label-green} |    [Check-in 02](checkins/02_checkin.html){.label .label-purple}    |                                                                                                                                 |
|                         | W 8/30  | R fundamentals                        |     [Slides 04](slides/04_lists-data-frames.html){.label .label-green}      |                                                                     |     [Lab 02](https://raw.githubusercontent.com/math167R-f23/math167R-f23.github.io/main/labs/02_lab.Rmd){.label .label-red}     |
|            3            | M 9/4   | *Labor Day (No Class)*                |                                                                             |                                                                     |                                                                                                                                 |
|                         | W 9/6   | Exploring data with R                 |       [Slides 05](slides/05_exploring-data.html){.label .label-green}       |                                                                     |     [Lab 03](https://raw.githubusercontent.com/math167R-f23/math167R-f23.github.io/main/labs/03_lab.Rmd){.label .label-red}     |
|            4            | M 9/11  | Exploring data with R                 |       [Slides 06](slides/06_factors-groups.html){.label .label-green}       |    [Check-in 03](checkins/03_checkin.html){.label .label-purple}    |                                                                                                                                 |
|                         | W 9/13  | Data visualization                    |      [Slides 07](slides/07_visualizing-data.html){.label .label-green}      |                                                                     |                                          [Lab 04](labs/04_lab.html){.label .label-red}                                          |
|            5            | M 9/18  | Data visualization                    |   [Slides 08](slides/08_advanced-visualization.html){.label .label-green}   |    [Check-in 04](checkins/04_checkin.html){.label .label-purple}    |                                                                                                                                 |
|                         | W 9/20  | Data visualization                    |        [Slides 09](slides/09_merging-data.html){.label .label-green}        |                                                                     |                                          [Lab 05](labs/05_lab.html){.label .label-red}                                          |
|            6            | M 9/25  | Data manipulation and management      |      [Slides 10](slides/10_data-management.html){.label .label-green}       |                                                                     |                                                                                                                                 |
|                         | W 9/27  | Data manipulation and management      |        [Slides 11](slides/11_spatial-data.html){.label .label-green}        |                                                                     |                                                                                                                                 |
|            7            | M 10/2  | Programming basics                    |     [Slides 12](slides/12_programming-basics.html){.label .label-green}     |                                                                     |                                                                                                                                 |
|                         | W 10/4  | Midterm project                       |                                                                             |                                                                     |                                                                                                                                 |
|            8            | M 10/9  | Programming basics                    |      [Slides 13](slides/13_functions-loops.html){.label .label-green}       |    [Check-in 05](checkins/05_checkin.html){.label .label-purple}    |                                                                                                                                 |
|                         | W 10/11 | Programming basics                    |  [Slides 14](slides/14_vectorization-recursion.html){.label .label-green}   |                                                                     |                                          [Lab 06](labs/06_lab.html){.label .label-red}                                          |
|            9            | M 10/16 | Programming basics                    |     [Slides 15](slides/15_environment-scope.html){.label .label-green}      |    [Check-in 06](checkins/06_checkin.html){.label .label-purple}    |                                                                                                                                 |
|                         | W 10/18 | Programming basics                    |         [Slides 16](slides/16_debugging.html){.label .label-green}          |                                                                     |                                          [Lab 07](labs/07_lab.html){.label .label-red}                                          |
|           10            | M 10/23 | Programming basics                    |  [Slides 17](slides/17_data-analysis-functions.html){.label .label-green}   |    [Check-in 07](checkins/07_checkin.html){.label .label-purple}    |                                                                                                                                 |
|                         | W 10/25 | Simulations                           |        [Slides 18](slides/18_simulations.html){.label .label-green}         |                                                                     |                                          [Lab 08](labs/08_lab.html){.label .label-red}                                          |
|           11            | M 10/30 | Simulations                           |      [Slides 19](slides/19_more-simulations.html){.label .label-green}      |    [Check-in 08](checkins/08_checkin.html){.label .label-purple}    |                                                                                                                                 |
|                         | W 11/1  | Simulations                           | [Slides 20](slides/20_simulation-based-inference.html){.label .label-green} |                                                                     |                                          [Lab 09](labs/09_lab.html){.label .label-red}                                          |
|           12            | M 11/6  | Simulations                           |    [Slides 21](slides/21_confidence-intervals.html){.label .label-green}    |    [Check-in 09](checkins/09_checkin.html){.label .label-purple}    |                                                                                                                                 |
|                         | W 11/8  | Statistical inference                 |     [Slides 22](slides/22_hypothesis-testing.html){.label .label-green}     |                                                                     |                                                                                                                                 |
|           13            | M 11/13 | Statistical inference                 |   [Slides 23](slides/23_hypothesis-testing-II.html){.label .label-green}    |                                                                     |                                                                                                                                 |
|                         | W 11/15 | Statistical inference                 |     [Slides 24](slides/24_linear-regression.html){.label .label-green}      |                                                                     |                                          [Lab 10](labs/10_lab.html){.label .label-red}                                          |
|           14            | M 11/20 | Statistical inference                 |    [Slides 25](slides/25_advanced-statistics.html){.label .label-green}     |                                                                     |                                                                                                                                 |
|                         | W 11/22 | *Thanksgiving (No Class)*             |                                                                             |                                                                     |                                                                                                                                 |
|           15            | M 11/27 | Prediction                            |         [Slides 26](slides/26_prediction.html){.label .label-green}         |    [Check-in 10](checkins/10_checkin.html){.label .label-purple}    |                                                                                                                                 |
|                         | W 11/29 | Prediction                            |                                                                             |                                                                     |                                                                                                                                 |
|           16            | M 12/4  | Final presentations and review        |                                                                             |                                                                     |                                                                                                                                 |
|                         | W 12/6  | Final presentations and review        |                                                                             |                                                                     |                                                                                                                                 |
:::

```{r echo = FALSE}
knitr::knit_exit()
```

|      |      |       | Prepare | Slides |                    AE                    | Labs | HW  | Exam | Project |
|------|------|-------|:-------:|:------:|:----------------------------------------:|:----:|:---:|:----:|:-------:|
| Week | Date | Topic |   📖    |   🖥️   | 📋 [Lab 01](hello){.label .label-purple} |  ✍️  |     |      |         |
